services: 
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 1234:5432
    env_file:
      - ./back-end/.env
    volumes:
      - pg:/var/lib/postgresql/data #tudo que estiver em data salvar em pg "tipo um pen driver"
  
  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - ./back-end/.env

  react_sorteador_app:
    container_name:  react_sorteador_app
    build: ./front-end  #onde fica o dockerfile
    volumes:
      - build_react:/var/www/html

  nginx_sorteador_app:
    container_name: nginx_sorteador_app
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db
      - node_app
      - react_sorteador_app

volumes:
  pg:
  build_react: 