services: 
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 1234:5432
    env_file:
      - ./back-end/.env
    volumes:
      - pg:/var/lib/postgresql/data #tudo que estiver em data salvar em pg "tipo um pen driver"
  
  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - ./back-end/.env

volumes:
  pg: